import requests
import random

def generate_opt():

    otp_random = str(int(random.random() * 1000000))
    print(otp_random)
    return otp_random

def send_opt(mobile):
    """
    Used for sending the OTP on users device to verify
    Service : FAST2SMS
    """
    otp_value = generate_opt()
    print("Entered into otp..." , otp_value)
    url = "https://www.fast2sms.com/dev/bulkV2"

    payload = "sender_id=UPCLIK&message=136307&variables_values="+otp_value+"|asdaswdx&route=dlt&numbers="+mobile
    headers = {
        'authorization': "tl4vJzuUZL7cYe90DNgKoRFqynaP6X2WpTshmQdkxbSwAHC5iEEQ4WOiKhnoeqjIHdZkgBNR2PXL19ra",
        'Content-Type': "application/x-www-form-urlencoded",
        'Cache-Control': "no-cache",
    }

    #apply rate limiting

    response = requests.request("POST", url, data=payload, headers=headers)

    print(response.text)
    return True


def verify_otp(mobile, otp):
    """
    Used for verifying the OTP send by clint and generated by system
    """
