# Generated by Django 4.0.4 on 2022-11-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_alter_userinfo_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='State',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='clg_city',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='clg_email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='college',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='username',
        ),
    ]
