# Generated by Django 4.0.4 on 2022-11-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_remove_userinfo_state_remove_userinfo_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='State',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='clg_city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='clg_email',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='college',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='dob',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
    ]
